spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: postgres
    password: mohammed
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    datbase: postgresql
